# Generated by Django 3.2.5 on 2021-07-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0002_santhosh'),
    ]

    operations = [
        migrations.CreateModel(
            name='mistorminor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
