# Generated by Django 3.2.5 on 2021-07-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp_2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fifth_standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question_no', models.IntegerField()),
                ('Question', models.CharField(max_length=1000)),
                ('Answer', models.CharField(max_length=100)),
                ('Option_A', models.CharField(max_length=30)),
                ('Option_B', models.CharField(max_length=30)),
                ('Option_C', models.CharField(max_length=30)),
                ('Option_D', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='seventh_standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question_no', models.IntegerField()),
                ('Question', models.CharField(max_length=1000)),
                ('Answer', models.CharField(max_length=100)),
                ('Option_A', models.CharField(max_length=30)),
                ('Option_B', models.CharField(max_length=30)),
                ('Option_C', models.CharField(max_length=30)),
                ('Option_D', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='sixth_standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question_no', models.IntegerField()),
                ('Question', models.CharField(max_length=1000)),
                ('Answer', models.CharField(max_length=100)),
                ('Option_A', models.CharField(max_length=30)),
                ('Option_B', models.CharField(max_length=30)),
                ('Option_C', models.CharField(max_length=30)),
                ('Option_D', models.CharField(max_length=30)),
            ],
        ),
    ]
